#book:
#    path: /
#    defaults: { _controller: "BookkeeperManagerBundle:Book:index" }
#
#book_show:
#    path: /show/{id}
#    defaults: { _controller: "BookkeeperManagerBundle:Book:show" }
#
#book_new:
#    path: /new
#    defaults: { _controller: "BookkeeperManagerBundle:Book:new" }
#
#book_edit:
#    path: /edit/{id}
#    defaults: { _controller: "BookkeeperManagerBundle:Book:edit" }
#
#book_create:
#     path: /create
#     defaults: { _controller: "BookkeeperManagerBundle:Book:create" }
##     requirements: { _method: post }
#
#book_update:
#    path: /update/{id}
#    defaults: { _controller: "BookkeeperManagerBundle:Book:update" }
##    requirements: { _method: put }
#
#book_delete:
#    path: /delete/{id}
#    defaults: { _controller: "BookkeeperManagerBundle:Book:delete"}
##    requirements: { _method: post|delete }
#
#delete_book_table:
#  path: /table
#  defaults: { _controller: "BookkeeperManagerBundle:Book:table"}
#
#author:
#  path: /author/index
#  defaults: { _controller: "BookkeeperManagerBundle:Author:index" }
#
#author_new:
#  path: /author/new
#  defaults: { _controller: "BookkeeperManagerBundle:Author:new" }
#
#author_create:
#  path: /author/create
#  defaults: { _controller: "BookkeeperManagerBundle:Author:create" }
